
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 13 00:25:43 CEST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CalculetteSymbol {
  /* terminals */
  public static final int INCREM = 43;
  public static final int RIGHT_DECAL = 37;
  public static final int FUNCTION = 6;
  public static final int LBRACKET = 17;
  public static final int POINTVIRG = 30;
  public static final int MULT = 33;
  public static final int CHAR = 24;
  public static final int GE = 49;
  public static final int CHAP = 54;
  public static final int CHARAA = 19;
  public static final int FOR_EACH = 59;
  public static final int REPEAT = 58;
  public static final int INT = 23;
  public static final int NO_LOGIC = 41;
  public static final int MINUS = 32;
  public static final int STATIC = 61;
  public static final int AND = 8;
  public static final int LT = 45;
  public static final int RPAR = 29;
  public static final int TYPE = 9;
  public static final int IN = 56;
  public static final int OR = 52;
  public static final int BOOL = 26;
  public static final int CLASS = 63;
  public static final int DIV = 34;
  public static final int MOT = 67;
  public static final int PLUS = 31;
  public static final int MAIN = 60;
  public static final int AND_COM = 51;
  public static final int IF = 12;
  public static final int ID = 69;
  public static final int LE = 47;
  public static final int EOF = 0;
  public static final int RETURN = 62;
  public static final int TILD = 42;
  public static final int RBRACKET = 18;
  public static final int TRUE = 21;
  public static final int ENTREPARENT = 50;
  public static final int error = 1;
  public static final int VAR_TYPE = 66;
  public static final int COMA = 36;
  public static final int PIPE = 48;
  public static final int NBR = 68;
  public static final int NULL = 20;
  public static final int EQEQ = 13;
  public static final int MOD = 35;
  public static final int BREAK = 7;
  public static final int EQ = 10;
  public static final int COLONS = 39;
  public static final int ARROW = 65;
  public static final int ELSE = 55;
  public static final int LBRACE = 15;
  public static final int STOP = 14;
  public static final int POINT = 64;
  public static final int WHILE = 57;
  public static final int LIST = 3;
  public static final int LET = 40;
  public static final int FLOAT = 25;
  public static final int THEN = 2;
  public static final int RBRACE = 16;
  public static final int LEFT_DECAL = 38;
  public static final int STRING = 70;
  public static final int LPAR = 28;
  public static final int DECREM = 44;
  public static final int DIFF = 53;
  public static final int STRINGSS = 27;
  public static final int FALSE = 22;
  public static final int STRUCT = 11;
  public static final int LIST_OF_TYPE = 5;
  public static final int GT = 46;
  public static final int PROCEDURE = 4;
}

