
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 11 13:58:30 CEST 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class CompSymbol {
  /* terminals */
  public static final int INCREM = 28;
  public static final int RIGHT_DECAL = 49;
  public static final int STRING_LITERAL = 65;
  public static final int FUNCTION = 63;
  public static final int LBRACKET = 8;
  public static final int MULT = 24;
  public static final int CHAR = 40;
  public static final int GE = 17;
  public static final int CHAP = 50;
  public static final int SEMIC = 10;
  public static final int FOR_EACH = 32;
  public static final int REPEAT = 34;
  public static final int INT = 39;
  public static final int NO_LOGIC = 30;
  public static final int MINUS = 22;
  public static final int BOOLEAN_LITERAL = 68;
  public static final int CHARACTER_LITERAL = 69;
  public static final int NOT = 13;
  public static final int AND = 11;
  public static final int LT = 14;
  public static final int RPAR = 7;
  public static final int TYPE = 60;
  public static final int LIST_OF_VAR_TYPE = 45;
  public static final int IN = 33;
  public static final int OR = 12;
  public static final int BOOL = 42;
  public static final int CLASS = 56;
  public static final int DIV = 25;
  public static final int POINTER_TYPE = 54;
  public static final int PLUS = 21;
  public static final int AND_COM = 47;
  public static final int IF = 2;
  public static final int LE = 16;
  public static final int EOF = 0;
  public static final int RETURN = 52;
  public static final int TILD = 51;
  public static final int RBRACKET = 9;
  public static final int TRUE = 59;
  public static final int error = 1;
  public static final int VAR_TYPE = 44;
  public static final int COMA = 38;
  public static final int PIPE = 31;
  public static final int POINTER_VAR_TYPE = 46;
  public static final int NULL = 57;
  public static final int EQEQ = 19;
  public static final int MOD = 26;
  public static final int EQ = 18;
  public static final int IF_WITHOUT_ELSE = 4;
  public static final int COLONS = 27;
  public static final int ARROW = 37;
  public static final int LBRACE = 61;
  public static final int ELSE = 3;
  public static final int POINT = 36;
  public static final int WHILE = 5;
  public static final int FLOAT = 41;
  public static final int LET = 35;
  public static final int RBRACE = 62;
  public static final int LEFT_DECAL = 48;
  public static final int STRING = 43;
  public static final int LPAR = 6;
  public static final int DECREM = 29;
  public static final int DIFF = 20;
  public static final int MINUS_U = 23;
  public static final int FLOAT_LITERAL = 67;
  public static final int FALSE = 58;
  public static final int STRUCT = 55;
  public static final int LIST_OF_TYPE = 53;
  public static final int GT = 15;
  public static final int INTEGER_LITERAL = 66;
  public static final int IDENTIFIER = 64;
}

